# Generated by Django 3.0.2 on 2020-01-18 18:05

from django.db import migrations, models
import marketplace.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_id', models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True)),
                ('author_email', models.EmailField(max_length=254)),
                ('author_name', models.CharField(max_length=50)),
                ('listing_title', models.CharField(max_length=140)),
                ('listing_description', models.TextField()),
                ('listing_price', models.FloatField()),
                ('listing_image', models.ImageField(upload_to=marketplace.models.upload_location)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
